authorName: default
experimentName: single_var_func
trialConcurrency: 1
maxExecDuration: 5h
maxTrialNum: 5000
trainingServicePlatform: local
#searchSpacePath: search_space_non_arch.json
searchSpacePath: search_space_arch.json
useAnnotation: false
tuner:
  builtinTunerName: GridSearch
trial:
#  command: python3 func_approx_nni.py quadratic
  command: python3 func_approx_nni.py
  codeDir: .
  gpuNum: 0
